"""Draw an illustrated top-down rice-and-curry plate for store screenshots.

The image is original artwork (no third-party licence) and is embedded only in
the screenshot integration test, never in the shipped app.

Output: frontend/mobile/integration_test/demo_plate.dart (base64 JPEG)
"""
import base64
import io
import random
from pathlib import Path

from PIL import Image, ImageDraw, ImageFilter

ROOT = Path(__file__).resolve().parents[2]
W, H = 1200, 720
rng = random.Random(7)


def blob(d: ImageDraw.ImageDraw, cx, cy, r, fill, n=28, jitter=0.12):
    import math
    pts = []
    for i in range(n):
        a = 2 * math.pi * i / n
        rr = r * (1 + rng.uniform(-jitter, jitter))
        pts.append((cx + rr * math.cos(a), cy + rr * 0.92 * math.sin(a)))
    d.polygon(pts, fill=fill)


def main() -> None:
    img = Image.new("RGB", (W, H), (120, 82, 52))
    d = ImageDraw.Draw(img)
    # Wooden table planks.
    for y in range(0, H, 90):
        shade = rng.randint(-12, 12)
        d.rectangle([0, y, W, y + 88], fill=(122 + shade, 84 + shade, 54 + shade))
        for _ in range(40):
            x = rng.randint(0, W)
            d.line([x, y + rng.randint(5, 80), x + rng.randint(60, 200), y + rng.randint(5, 80)],
                   fill=(105 + shade, 70 + shade, 44 + shade), width=2)
    img = img.filter(ImageFilter.GaussianBlur(1.2))
    d = ImageDraw.Draw(img)

    # Plate shadow, rim and well.
    sh = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    ImageDraw.Draw(sh).ellipse([300, 70, 940, 690], fill=(0, 0, 0, 110))
    img.paste(sh.filter(ImageFilter.GaussianBlur(22)), (0, 0), sh.filter(ImageFilter.GaussianBlur(22)))
    d.ellipse([280, 40, 920, 680], fill=(246, 244, 238))
    d.ellipse([330, 90, 870, 630], fill=(236, 233, 226))

    # Rice mound with grains.
    blob(d, 540, 300, 150, (250, 248, 240), jitter=0.08)
    for _ in range(900):
        x, y = rng.gauss(540, 70), rng.gauss(300, 65)
        if (x - 540) ** 2 + (y - 300) ** 2 < 140 ** 2:
            d.ellipse([x - 5, y - 2, x + 5, y + 2], fill=rng.choice([(255, 255, 250), (235, 230, 215), (245, 242, 230)]))

    # Dhal curry (yellow) with mustard seeds.
    blob(d, 720, 430, 95, (232, 170, 40))
    blob(d, 715, 425, 80, (240, 186, 60))
    for _ in range(80):
        x, y = rng.gauss(715, 35), rng.gauss(425, 30)
        d.ellipse([x - 3, y - 3, x + 3, y + 3], fill=(70, 45, 20))

    # Chicken curry (deep red-brown) with pieces.
    blob(d, 470, 470, 105, (150, 52, 26))
    blob(d, 470, 470, 92, (170, 66, 30))
    for _ in range(9):
        x, y = rng.gauss(470, 40), rng.gauss(470, 35)
        blob(d, x, y, rng.randint(18, 28), (205, 130, 75), n=12, jitter=0.25)
    for _ in range(30):  # curry leaves
        x, y = rng.gauss(470, 55), rng.gauss(470, 50)
        d.ellipse([x - 9, y - 4, x + 9, y + 4], fill=(40, 90, 30))

    # Pol sambol (coconut sambol, orange-red flakes).
    for _ in range(500):
        x, y = rng.gauss(705, 28), rng.gauss(250, 26)
        c = rng.choice([(240, 120, 70), (225, 95, 55), (250, 160, 110), (255, 235, 220)])
        d.ellipse([x - 4, y - 3, x + 4, y + 3], fill=c)

    img = img.filter(ImageFilter.SMOOTH)
    buf = io.BytesIO()
    img.save(buf, "JPEG", quality=82)
    data = base64.b64encode(buf.getvalue()).decode()

    out = ROOT / "frontend/mobile/integration_test/demo_plate.dart"
    out.parent.mkdir(parents=True, exist_ok=True)
    chunks = [data[i:i + 100] for i in range(0, len(data), 100)]
    body = "\n".join(f"  '{c}'" for c in chunks)
    out.write_text(
        "// GENERATED by store-assets/_tools/make_demo_plate.py - do not edit.\n"
        "// Illustrated meal photo used only by the store-screenshot test.\n\n"
        "const demoPlateJpegBase64 =\n" + body + ";\n"
    )
    img.save(ROOT / "store-assets/_tools/demo_plate_preview.jpg", quality=82)
    print(f"wrote {out.relative_to(ROOT)} ({len(buf.getvalue()) // 1024} KB JPEG)")


if __name__ == "__main__":
    main()
